### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by edsu** [sul-dlss/dlme-transform#1017]
The docker build appears to be failing, and it doesn't appear to be related to recent dependency updates, since checking out an earlier version shows the same problem.

It seems like it is related to how PyYAML is being installed?

```
7.013 Executing busybox-1.31.1-r9.trigger
7.021 OK: 246 MiB in 78 packages
7.048 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
7.172 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
7.283 (1/4) Installing py-setuptools (42.0.2-r0)
7.378 (2/4) Installing py2-pip (18.1-r0)
7.565 (3/4) Installing python2-dev (2.7.18-r0)
7.850 (4/4) Installing python-dependencies (20230725.152716)
7.850 Executing busybox-1.31.1-r9.trigger
7.857 OK: 271 MiB in 82 packages
8.972 Collecting awscli
10.43   Downloading https://files.pythonhosted.org/packages/aa/24/e098cf5ce28a764bca174e88f4ccb70754e9f049c9bf986e582aedcb7420/awscli-1.19.112-py2.py3-none-any.whl (3.6MB)
11.45 Collecting botocore==1.20.112 (from awscli)
12.72   Downloading https://files.pythonhosted.org/packages/c7/ea/11c3beca131920f552602b98d7ba9fc5b46bee6a59cbd48a95a85cbb8f41/botocore-1.20.112-py2.py3-none-any.whl (7.7MB)
13.65 Collecting s3transfer<0.5.0,>=0.4.0 (from awscli)
13.71   Downloading https://files.pythonhosted.org/packages/63/d0/693477c688348654ddc21dcdce0817653a294aa43f41771084c25e7ff9c7/s3transfer-0.4.2-py2.py3-none-any.whl (79kB)
13.73 Collecting colorama<0.4.4,>=0.2.5 (from awscli)
13.81   Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
13.82 Collecting PyYAML<5.5,>=3.10 (from awscli)
13.99   Downloading https://files.pythonhosted.org/packages/a0/a4/d63f2d7597e1a4b55aa3b4d6c5b029991d3b824b5bd331af8d4ab1ed687d/PyYAML-5.4.1.tar.gz (175kB)
14.16   Installing build dependencies: started
17.31   Installing build dependencies: finished with status 'done'
17.54     Complete output from command python setup.py egg_info:
17.54     running egg_info
17.54     creating pip-egg-info/PyYAML.egg-info
17.54     writing pip-egg-info/PyYAML.egg-info/PKG-INFO
17.54     writing top-level names to pip-egg-info/PyYAML.egg-info/top_level.txt
17.54     writing dependency_links to pip-egg-info/PyYAML.egg-info/dependency_links.txt
17.54     writing manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
17.54     Traceback (most recent call last):
17.54       File "<string>", line 1, in <module>
17.54       File "/tmp/pip-install-8G9Q_I/PyYAML/setup.py", line 295, in <module>
17.54         python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
17.54         return distutils.core.setup(**attrs)
17.54       File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
17.54         dist.run_commands()
17.54       File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
17.54         self.run_command(cmd)
17.54       File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
17.54         cmd_obj.run()
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
17.54         self.find_sources()
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
17.54         mm.run()
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
17.54         self.add_defaults()
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
17.54         sdist.add_defaults(self)
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
17.54         self._add_defaults_ext()
17.54       File "/tmp/pip-build-env-0D6L_p/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext
17.54         self.filelist.extend(build_ext.get_source_files())
17.54       File "/tmp/pip-install-8G9Q_I/PyYAML/setup.py", line 201, in get_source_files
17.54         self.cython_sources(ext.sources, ext)
17.54       File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
17.54         raise AttributeError, attr
17.54     AttributeError: cython_sources
17.54
17.54     ----------------------------------------
17.77 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8G9Q_I/PyYAML/
------
Dockerfile:15
--------------------
  14 |
  15 | >>> RUN apk add --no-cache \
  16 | >>>     curl \
  17 | >>>     zip \
  18 | >>>     python \
  19 | >>>     libxml2-dev \
  20 | >>>     libxslt-dev \
  21 | >>>     jq \
  22 | >>>     util-linux \
  23 | >>>     && apk add --no-cache --virtual build-dependencies \
  24 | >>>       build-base \
  25 | >>>     && apk add --no-cache --virtual python-dependencies \
  26 | >>>     py-pip \
  27 | >>>     python-dev \
  28 | >>>     && pip install awscli \
  29 | >>>     && apk del python-dependencies \
  30 | >>>     && gem install bundler
  31 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache     curl     zip     python     libxml2-dev     libxslt-dev     jq     util-linux     && apk add --no-cache --virtual build-dependencies       build-base     && apk add --no-cache --virtual python-dependencies     py-pip     python-dev     && pip install awscli     && apk del python-dependencies     && gem install bundler" did not complete successfully: exit code: 1
```

**Comment by edsu** [comment]
I'm a little bit confused because it looks like we test with ruby3 but build an image with ruby 2.7?
