### ISSUE TITLE
Transform error does not result in SNS message

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dlme-transform#106]
```
2019-03-06T13:42:40+00:00 INFO finished Traject::Indexer#process: 1 records in 0.006 seconds; 163.0 records/second overall.
/usr/local/bundle/gems/traject-3.0.0/lib/traject/indexer.rb:206:in `rescue in block in load_config_file': Error loading configuration file config/bnf_common_config.rb:6 LoadError:cannot load such file -- macros/srw (Traject::Indexer::ConfigLoadError)
from /usr/local/bundle/gems/traject-3.0.0/lib/traject/indexer.rb:203:in `block in load_config_file'
from /usr/local/bundle/gems/traject-3.0.0/lib/traject/indexer.rb:202:in `open'
from /usr/local/bundle/gems/traject-3.0.0/lib/traject/indexer.rb:202:in `load_config_file'
from /opt/traject/lib/transformer.rb:33:in `block (2 levels) in transformer'
from /opt/traject/lib/transformer.rb:33:in `each'
from /opt/traject/lib/transformer.rb:33:in `block in transformer'
from /opt/traject/lib/transformer.rb:32:in `tap'
from /opt/traject/lib/transformer.rb:32:in `transformer'
from /opt/traject/lib/transformer.rb:25:in `transform'
from /opt/traject/lib/cli.rb:73:in `block in transform_all'
from /opt/traject/lib/cli.rb:67:in `each'
from /opt/traject/lib/cli.rb:67:in `transform_all'
from /opt/traject/lib/cli.rb:53:in `transform'
from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
from exe/transform:8:in `<main>'
```
then
```
Sending to S3
Completed 256.0 KiB/372.3 KiB (2.3 MiB/s) with 1 file(s) remaining
Completed 372.3 KiB/372.3 KiB (2.1 MiB/s) with 1 file(s) remaining
upload: output/output-20190306134236.ndjson to s3://dlme-metadata-dev/output-20190306134236.ndjson
mv: can't rename 'output/summary-20190306134236.json': No such file or directory
jq: error: Could not open file output/summary-20190306134236.json.tmp: No such file or directory
rm: can't remove 'output/summary-20190306134236.json.tmp': No such file or directory
Sending notification to SNS
An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Empty message
```

Expected result:
Should send SNS message containing the error.

**Comment by justinlittman** [comment]
Problem is that not most recent code deployed.
