### ISSUE TITLE
Require hash keys in IR to not equal 'none'

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#675]
As the DLME data manager, I need tests to ensure that no hashes in the intermediate representation are assigned `none` keys. Most metadata fields are assigned language keys; the default if not specified is ‘none’. No language key should be ‘none’. Since we are using BCP47 codes we can, at least, determine the script of the language. 

Requirements:
- [ ] Fails when `none` found, stop processing records; the transform process will stop and an error message with problematic field, values, and dlme_source_file will be reported to the terminal.
- [ ] Fails, only in debug mode, if field found with ‘*-Arab’ that includes Latin script; the transform process will stop and an error message with problematic field, values, and dlme_source_file will be reported to the terminal.
- [ ] Fails, only in debug mode, if field found with ‘*-Latn’ that includes Arabic script; the transform process will stop and an error message with problematic field, values, and dlme_source_file will be reported to the terminal.

**Comment by jmartin-sul** [comment]
after discussing w/ @aaron-collier and @jacobthill in planning meeting on tues morning, we decided that we would just raise an error and allow the transform to fail fast when we run into a situation where the IR key would fallback to `'none'`.  however, when playing with that implementation yesterday, i discovered that we'd run into this situation frequently, even just within the aims data set, and so was worried about committing that change to `main` without first fixing the data and/or the transform configs (so as to prevent `'none'` from appearing as a key in the IR hashes).

discussed w/ @jacobthill just now, and we decided to do the following:
- [ ] to start, instead of raising an error, we'll log a message anytime we'd fall back to a hash key of `'none'`.
- [ ]  i'll run that code over the entirety of the dlme-metadata data set, collecting the output
- [ ]  i'll grep for the log message and give that output to jacob
- [ ]  he'll fix the records/configs as needed
- [ ]  once the data and/or configs are fixed up so that we don't have anymore of this error, we'll modify the code to raise an error in this situation, and then we'll fail fast and fix immediately if/when this problem gets introduced again in the future (by new data and/or configs).

jacob confirms that the hash keys always represent language (which i was unsure about, since i'm still relatively new to this project).

**Comment by jmartin-sul** [comment]
another thing we discussed in tuesday planning, which i think we intend to split into a separate ticket, was adding some sort of warning when the detected script doesn't match the specified language, if a language is specified (i believe this is captured in this issue's description as "Fails... if field found with ‘*-Arab’ that includes Latin script" and "Fails... if field found with ‘*-Latn’ that includes Arabic script".

**Comment by jmartin-sul** [comment]
here's a grep for the new log message that catches missing language when running the transform script:

[missing_language_key_errors.log](https://github.com/sul-dlss/dlme-transform/files/6866657/missing_language_key_errors.log)

this is the transform output from `exe/transform -w` run across the entirety of [dlme-metadata](https://github.com/sul-dlss/dlme-metadata), filtered for the error message added in #762.

looks like there are currently 610 occurrences of this issue.

**Comment by jmartin-sul** [comment]
@jacobthill, it turns out that if i modify #762 so that it raises instead of logging a warning, and then i run the transform without the `-w` flag (or if i run the unit tests), i get an error like:

running `exe/transform`:

```
E, [2021-07-26T21:37:30.502144 #43089] ERROR -- : traject_configs/auc_oai_kraus_meyerhof_config.rb: key=cho_description; value=Index of offprints related to the study of Arab medicine.; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
2021-07-26T21:37:30-07:00 ERROR Unexpected error on record <record #1 (data/auc/oai/kraus-meyerhof/data/kraus-meyerhof-103.xml #1), output_id:p15795coll1/105>
    while executing (each_record at traject_configs/auc_oai_kraus_meyerhof_config.rb:93)

    Record: <?xml version="1.0"?>
<record xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <header>
    <identifier>oai:cdm15795.contentdm.oclc.org:p15795coll1/105</identifier>
    <datestamp>2012-11-07</datestamp>
    <setSpec>p15795coll1</setSpec>
  </header>
  <metadata>
    <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
      <dc:title>Medecine Arabe II</dc:title>
      <dc:title>Kraus-Meyerhof Offprints volume 34</dc:title>
      <dc:contributor>Kraus, Paul, 1904-1944</dc:contributor>
      <dc:contributor>American University in Cairo. Rare Books and Special Collections Library</dc:contributor>
      <dc:description>Index of offprints related to the study of Arab medicine.</dc:description>
      <dc:subject>Medicine, Arab</dc:subject>
      <dc:date>1960; 1961; 1962; 1963; 1964; 1965; 1966; 1967; 1968; 1969; 1970; 1971; 1972; 1973; 1974; 1975; 1976; 1977; 1978; 1979; 1980; 1981; 1982; 1983; 1984; 1985; 1986; 1987; 1988; 1989</dc:date>
      <dc:type>Still Image; Text</dc:type>
      <dc:format>application/pdf</dc:format>
      <dc:format>16.6 x 21 cm.; 4 p.</dc:format>
      <dc:format>indexes (reference sources)</dc:format>
      <dc:language>Arabic; German; English; French; Italian</dc:language>
      <dc:identifier>SC-1000-01-Volume-034-Index</dc:identifier>
      <dc:relation>Kraus-Meyerhof Offprints</dc:relation>
      <dc:source>Kraus-Meyerhof Offprints Collection; Rare Books and Special Collections Library; American University in Cairo</dc:source>
      <dc:rights>Copyright 2012, American University in Cairo. All rights reserved.</dc:rights>
      <dc:rights>To inquire about permissions or reproductions, contact the Rare Books and Special Collections Library, The American University in Cairo at +20.2.2615.3676 or rbscl-ref@aucegypt.edu.</dc:rights>
      <dc:identifier>http://cdm15795.contentdm.oclc.org/cdm/ref/collection/p15795coll1/id/105</dc:identifier>
    </oai_dc:dc>
  </metadata>
</record>

    Exception: Macros::EachRecord::UnspecifiedLanguageError: traject_configs/auc_oai_kraus_meyerhof_config.rb: key=cho_description; value=Index of offprints related to the study of Arab medicine.; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
    /Users/suntzu/software_dev_projects/dlme-transform/lib/macros/each_record.rb:42:in `block (3 levels) in convert_to_language_hash'

[ERROR] traject_configs/auc_oai_kraus_meyerhof_config.rb: key=cho_description; value=Index of offprints related to the study of Arab medicine.; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
```

running the unit tests:

```
E, [2021-07-26T20:53:16.114116 #34405] ERROR -- : traject_configs/bnf_ideo_config.rb: key=cho_contributor; value=Kamāl al-Dīn, ʿUṯmān; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
2021-07-26T20:53:16-07:00 ERROR Unexpected error on record <record #1 (data/bnf/ideo/data/ideo-1.xml #1), output_id:https://gallica.bnf.fr/ark:/12148/bpt6k9105978p>
    while executing (each_record at traject_configs/bnf_ideo_config.rb:21)

    Record: <?xml version="1.0"?>
<srw:record xmlns:srw="http://www.loc.gov/zing/srw/" xmlns:ns7="http://gallica.bnf.fr/namespaces/gallica/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:onix_dc="http://bibnum.bnf.fr/NS/onix_dc/" xmlns:onix="http://www.editeur.org/onix/2.1/reference/" xmlns:dc="http://purl.org/dc/elements/1.1/">
            <srw:recordSchema>http://www.openarchives.org/OAI/2.0/OAIdc.xsd</srw:recordSchema>
            <srw:recordPacking>xml</srw:recordPacking>
            <srw:recordData>
                <oai_dc:dc>
                    <dc:contributor>Kam&#x101;l al-D&#x12B;n, &#x2BF;U&#x1E6F;m&#x101;n. Correcteur</dc:contributor>
                    <dc:creator>Kam&#x101;l al-D&#x12B;n, &#x2BF;U&#x1E6F;m&#x101;n. Auteur du texte</dc:creator>
                    <dc:description>[Ra&#x2BE;s al-&#x1E25;ikma&#x1E97;. 1891]</dc:description>
                    <dc:description>Num&#xE9;ris&#xE9; par le partenaire</dc:description>
                    <dc:description>Appartient &#xE0; l&#x2019;ensemble documentaire : BbLevt0</dc:description>
                    <dc:description>Num&#xE9;ris&#xE9; par le partenaire</dc:description>
                    <dc:format>32 pages ; 13 &#xD7; 19 cm</dc:format>
                    <dc:format>Nombre total de vues : 41</dc:format>
                    <dc:identifier>https://gallica.bnf.fr/ark:/12148/bpt6k9105978p</dc:identifier>
                    <dc:language>ara</dc:language>
                    <dc:language>arabe</dc:language>
                    <dc:relation>Notice du catalogue : http://catalogue.bnf.fr/ark:/12148/cb44588848p</dc:relation>
                    <dc:relation>Notice dans un autre catalogue : http://alkindi.ideo-cairo.org/manifestation/8045</dc:relation>
                    <dc:rights>domaine public</dc:rights>
                    <dc:rights>public domain</dc:rights>
                    <dc:source>Institut dominicain d'&#xE9;tudes orientales, 9-759-31</dc:source>
                    <dc:title>&#x643;&#x62A;&#x627;&#x628; &#x631;&#x623;&#x633; &#x627;&#x644;&#x62D;&#x643;&#x645;&#x629; : &#x648;&#x64A;&#x644;&#x64A;&#x647; &#x623;&#x645;&#x62B;&#x627;&#x644; &#x633;&#x64A;&#x62F;&#x646;&#x627; &#x639;&#x644;&#x64A; &#x643;&#x631;&#x645; &#x627;&#x644;&#x644;&#x647; &#x648;&#x62C;&#x647;&#x647; (&#x627;&#x644;&#x637;&#x628;&#x639;&#x629; &#x627;&#x644;&#x623;&#x648;&#x644;&#x649;) / &#x62A;&#x623;&#x644;&#x64A;&#x641; &#x627;&#x644;&#x645;&#x639;&#x62A;&#x635;&#x645; &#x628;&#x62D;&#x628;&#x644; &#x627;&#x644;&#x644;&#x647; &#x627;&#x644;&#x645;&#x62A;&#x64A;&#x646; &#x639;&#x62B;&#x645;&#x627;&#x646; &#x643;&#x645;&#x627;&#x644; &#x627;&#x644;&#x62F;&#x64A;&#x646;</dc:title>
                    <dc:title>Kit&#x101;b Ra&#x2BE;s al-&#x1E25;ikma&#x1E97; : wa-yal&#x12B;hi Am&#x1E6F;&#x101;l sayyidin&#x101; &#x2BF;Al&#x12B; karama All&#xE2;h wa&#x1E7;hahu (&#x627;&#x644;&#x637;&#x628;&#x639;&#x629; &#x627;&#x644;&#x623;&#x648;&#x644;&#x649;) / Ta&#x2BE;l&#x12B;f al-mu&#x2BF;ta&#x1E63;im bi-&#x1E25;abli All&#xE2;h al-mat&#x12B;n &#x2BF;U&#x1E6F;m&#x101;n Kam&#x101;l al-D&#x12B;n</dc:title>
                    <dc:type>text</dc:type>
                    <dc:type>monographie imprim&#xE9;e</dc:type>
                    <dc:type>monographie imprim&#xE9;e</dc:type>
                </oai_dc:dc>
            </srw:recordData>
            <srw:recordIdentifier>ark</srw:recordIdentifier>
            <srw:recordPosition>0</srw:recordPosition>
            <srw:extraRecordData>
                <epubFile/>
                <infoSupModifiable/>
                <link>https://gallica.bnf.fr/ark:/12148/bpt6k9105978p </link>
                <nqamoyen>0.0</nqamoyen>
                <thumbnail>https://gallica.bnf.fr/ark:/12148/bpt6k9105978p.thumbnail</thumbnail>
                <typedoc>monographies</typedoc>
            </srw:extraRecordData>
        </srw:record>

    Exception: Macros::EachRecord::UnspecifiedLanguageError: traject_configs/bnf_ideo_config.rb: key=cho_contributor; value=Kamāl al-Dīn, ʿUṯmān; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
    /Users/suntzu/software_dev_projects/dlme-transform/lib/macros/each_record.rb:42:in `block (3 levels) in convert_to_language_hash'
```

**Comment by jmartin-sul** [comment]
@jacobthill, if you want to experiment with the version that raises, you can checkout the `disallow-none-for-IR-keys` branch (you'll want to `git fetch` the latest, since i just pushed the version that raises an error when language is unspecified, instead of just logging).

also, this was surprising, since i ran `exe/transform -w` after merging #763 and rebasing on main, and no errors were raised (even though i'm 99% sure i'd already made the change in the second commit of #762). 🤷

**Comment by jmartin-sul** [comment]
see also: https://app.circleci.com/pipelines/github/sul-dlss/dlme-transform/1645/workflows/9f0d8979-6cd4-4ef7-911a-0f5957c77028/jobs/2504?invite=true#step-109-270

**Comment by jmartin-sul** [comment]
@jacobthill merging #766 fixed the above error from the tests, but now i'm seeing:

```
E, [2021-07-27T17:06:54.901378 #97481] ERROR -- : traject_configs/bodleian_arabic_config.rb: key=cho_spatial; value=Egypt; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
2021-07-27T17:06:54-07:00 ERROR Unexpected error on record <record #1 (data/bodleian/arabic/data/Arabic-1.json #1), output_id:748a9d50-5a3a-440e-ab9d-567dd68b6abb>
    while executing (each_record at traject_configs/bodleian_arabic_config.rb:90)

    Record: {"rendering"=>"https://digital.bodleian.ox.ac.uk/inquire/p/748a9d50-5a3a-440e-ab9d-567dd68b6abb", "thumbnail"=>"https://iiif.bodleian.ox.ac.uk/iiif/image/36ebabd9-4d62-4d8e-8e7b-1afd048e872e/full/256,/0/default.jpg", "description_top"=>"Kitāb Gharāʼib al-funūn wa-mulaḥ al-ʻuyūn (كتاب غرائب الفنون وملح العيون) ('The Book of Curiosities')", "homepage"=>"<span><a href=\"https://digital.bodleian.ox.ac.uk/inquire/p/748a9d50-5a3a-440e-ab9d-567dd68b6abb\">View on Digital Bodleian</a></span>", "catalogue_description"=>"<a href=\"https://www.fihrist.org.uk/catalog/manuscript_783\">Fihrist: Union Catalogue of Manuscripts from the Islamicate World</a>", "title"=>"Kitāb Gharāʼib al-funūn wa-mulaḥ al-ʻuyūn (كتاب غرائب الفنون وملح العيون) ('The Book of Curiosities')", "shelfmark"=>"Bodleian Library MS. Arab. c. 90", "language"=>"Arabic", "date_statement"=>"1190–1210", "place_of_origin"=>"Egypt", "description"=>"Binding: Disbound, binding retained. 18th or 19th century Ottoman binding in poor condition.", "provenance"=>"Bought from Sam Fogg, 2002.", "record_origin"=>"Description in part based on Savage-Smith, E. and Rapoport, Y. (2013), An Eleventh-Century Egyptian Guide to the Universe, pp. 2-4.", "collection"=>"Arabic Manuscripts and Maps", "acknowledgements"=>"Annotations converted by Data Futures (https://www.data-futures.org/).", "digitization_sponsor"=>"Arts and Humanities Research Council", "record_created"=>"2018-04-11T16:03:03Z", "holding_institution"=>"Bodleian Libraries, University of Oxford"}
    Exception: Macros::EachRecord::UnspecifiedLanguageError: traject_configs/bodleian_arabic_config.rb: key=cho_spatial; value=Egypt; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
...
Failures:

  1) integration with Traject configs maps a sampling of configs without errors
     Failure/Error:
       expect do
         configs.each do |data_filepath, config|
           Dlme::Transformer.new(
             input_filepath: data_filepath,
             config_filepaths: config['trajects'].map { |traject| "#{Settings.defaults.traject_dir}/#{traject}" },
             settings: config.fetch('settings', {})
           ).transform
         rescue StandardError => e
           raise "error raised mapping #{config['settings']['inst_id']} for #{data_filepath}: #{e.class}: #{e.message}"
         end
     
       expected no Exception, got #<RuntimeError: error raised mapping bodleian for data/bodleian/arabic/data/Arabic-1.json: Macros::Ea...s IR language key, language must be specified.  Check source data and/or traject config for errors.> with backtrace:
         # ./spec/integration/traject_configs_spec.rb:22:in `rescue in block (4 levels) in <top (required)>'
         # ./spec/integration/traject_configs_spec.rb:20:in `block (4 levels) in <top (required)>'
         # ./spec/integration/traject_configs_spec.rb:15:in `each'
         # ./spec/integration/traject_configs_spec.rb:15:in `block (3 levels) in <top (required)>'
         # ./spec/integration/traject_configs_spec.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/integration/traject_configs_spec.rb:14:in `block (2 levels) in <top (required)>'
```

https://app.circleci.com/pipelines/github/sul-dlss/dlme-transform/1654/workflows/2c9a2d8e-92c6-4dad-bcd2-f58e253304c3/jobs/2518?invite=true#step-109-200

**Comment by jmartin-sul** [comment]
current error after rebasing #762 on `main` just now (after merging #770):

```
E, [2021-07-28T21:31:29.156298 #437] ERROR -- : traject_configs/cambridge_hebrew_config.rb: key=cho_title; value=Schematic map; 'none' not allowed as IR language key, language must be specified.  Check source data and/or traject config for errors.
2021-07-28T21:31:29+00:00 ERROR Unexpected error on record <record #1 (data/cambridge/hebrew/hebrew-1.xml #1), output_id:cambridge_hebrew-1>
    while executing (each_record at traject_configs/cambridge_hebrew_config.rb:120)
```

https://app.circleci.com/pipelines/github/sul-dlss/dlme-transform/1669/workflows/f7bbc965-9218-4f2c-902b-83eaf6523675/jobs/2537?invite=true#step-109-187
